### ISSUE TITLE
how to generate complete json file with python tools/test.py

### ISSUE THREAD

**Issue by tianyufang1958** [NVlabs/mask-auto-labeler#10]
Hello, I ran the following command 
python tools/test.py configs/MALMask/solov2_r50_fpn_3x_coco_mal.py work_dirs/solov2_r50_fpn_3x_coco_mal/latest.pth --format-only --eval-options "jsonfile_prefix=val-dev

and successfully generated val-dev.segm.json file, however, this annotation file is not complete without information like file names. It only contains segmentation information.
I tried to add the missing information myself but kept getting format errors.
This might be a mmdet issue, but I would appreciate if you could give me some advice how to generate a complete json file.

**Comment by voidrank** [comment]
Hi @tianyufang1958 , can you show me the logs?
