### ISSUE TITLE
MAL model deployment

### ISSUE THREAD

**Issue by d710055071** [NVlabs/mask-auto-labeler#4]
I want to export the MAL model, and then use python for reasoning to get the mask img. What should I do?

**Comment by voidrank** [comment]
Hi @d710055071 ,

1. Please kindly read the README and then make your questions more specific.
2. There will be another open-source solution released next month. I will update the README and point everyone to that repo/lib.

Best,

Shiyi

**Comment by tianyufang1958** [comment]
Hi @voidrank 

I successfully ran python main.py and implement the inference
 python main.py --resume work_dirs/coco/last.ckpt --label_dump_path psuedo --not_eval_mask, I got two files psuedo and psuedo.result. 
I don't know what theses two files are and I don't a resulting folder of psuedo labelled images. Should I expect a folder of labelled images? I can see the annotation data inside the psuedo.result, but why it is not .json. What is the information in psuedo?

**Comment by voidrank** [comment]
The mask labels should be inside JSON file as far as I remember.

**Comment by tianyufang1958** [comment]
> The mask labels should be inside JSON file as far as I remember.

Unfortunately it doesn't generate .json for me. I have to add the json extension myself. I am not sure if I did correctly.

**Comment by voidrank** [comment]
oh I forgot, you need to add `.json` on your own
